<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script type="text/javascript">
$(function() {
}); 

		</script>
</head>
<body>
<a href="/chat/moiety" class="w3-btn w3-black w3-round-large w3-padding-small">二分一</a>
<a href="/chat/highstock"  class="w3-btn w3-black w3-round-large w3-padding-small">舊圖</a>
<a href="/chat/info"  class="w3-btn w3-black w3-round-large w3-padding-small">近日買賣數字</a>
    
</body>
</html>
