<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript">
$(function() {
    /*
	$.getJSON('http://www.highcharts.com/samples/data/jsonp.php?filename=aapl-ohlc.json&callback=?', function(data) {
        console.log(data);
    });
     */
	$.getJSON('/ajax/twii', function(data) {
		// create the chart
        var weeks = ['日', '一', '二', '三', '四', '五', '六'];
		chart = new Highcharts.StockChart({
			chart : {
				renderTo : 'container'
			},
			rangeSelector : {
                buttons: [{
                    count: 6,
                    type: 'month',
                    text: '6m'
                }, {
                    count: 1,
                    type: 'month',
                    text: '1m'
                }, {
                    count: 3,
                    type: 'month',
                    text: '3m'
                }, {
                    count: 1,
                    type: 'year',
                    text: '1y'
                }, {
                    type: 'all',
                    text: 'All'
                }],
                selected: 0
			},
			title : {
				text : '台灣加權指數'
			},
            tooltip: {
                shared: true,
                formatter: function(){
                    //console.log(this.points);
                    if (_.isUndefined(this.y)) {
                        return this.point.text;
                    }
                    var d = new XDate(this.x);
                    var w = d.getDay();
                    var p = '<b>'+ d.toString('yyyy/MM/dd(') + weeks[w] +')</b><br/>';

                    $.each(this.points, function(i, series){
                            p += '開盤: ' + series.point.open + '<br/>'+
                                '最高: ' + series.point.high + '<br/>'+
                                '最低: ' + series.point.low + '<br/>'+
                                '收盤: ' + series.point.close +'<br/>'+
                                '均價: ' + ((series.point.high + series.point.low)/2).toFixed(2) +'<br/>';
                    });
                    return p;
                }
            },
            plotOptions: {
                series: {
                    cursor: 'pointer',
                    point: {
                        events: {
                            click: function() {
                                chart.showLoading('Loading data...');
                                var d = new XDate(this.x);
                                $.post('/ajax/getDayInfo', {day: d.toString('yyyy-MM-dd')}, function(response) {
                                    if (!response.error) {
                                        $('#info').html(response.content);
                                    }
                                    chart.hideLoading();
                                });
                            }
                        }
                    },
                    marker: {
                        lineWidth: 1
                    }
                },
                candlestick: {
                    color: 'green',
                    upColor: 'red'
                }
            },
			series : [{
				type : 'candlestick',
				name : '台灣加權指數',
                id: 'twii',
				data : data,
				dataGrouping : {
					units : [
						['day', // unit name
						[1, 5] // allowed multiples
					]]
				}
            },{
                type : 'flags',
                data : [{
                    x : Date.UTC(2012, 11, 11),
                    title : '多',
                    text : '單日反轉'
                }, {
                    x : Date.UTC(2012, 11, 25),
                    title : '多',
                    text : '突破雙星, 產生支撐7599.22'
                }, {
                    x : Date.UTC(2013, 0, 17),
                    title : '出',
                    text : '收7616.64 測試 7599.22(2012/12/25) 支撐有效,空單出場'
                }, {
                    x : Date.UTC(2013, 0, 18),
                    title : '多',
                    text : '母子晨星'
                }, {
                    x : Date.UTC(2013, 0, 23),
                    title : '空',
                    text : '單日反轉'
                }, {
                    x : Date.UTC(2013, 0, 25),
                    title : '多',
                    text : '單日反轉'
                }, {
                    x : Date.UTC(2013, 0, 29),
                    title : '多',
                    text : '突破雙星+島狀反轉'
                }, {
                    x : Date.UTC(2013, 1, 1),
                    title : '破',
                    text : '收7855.97 突破壓力 7855.16(2013/01/03) 壓力變支撐等測試'
                }, {
                    x : Date.UTC(2013, 1, 4),
                    title : '多',
                    text : '上升三法'
                }, {
                    x : Date.UTC(2013, 1, 5),
                    title : '多',
                    text : '7855.16(2013/01/03) 支撐有效'
                }, {
                    x : Date.UTC(2013, 1, 20),
                    title : '空',
                    text : '高檔吊首~多單該出場了-隔日確認空單進場'
                }, {
                    x : Date.UTC(2013, 1, 23),
                    title : '壓',
                    text : '7988.99(2013/02/21) 壓力有效'
                }, {
                    x : Date.UTC(2013, 1, 27),
                    title : '多',
                    text : '自營SC出光光'
                }, {
                    x : Date.UTC(2013, 2, 1),
                    title : '多',
                    text : '島狀反轉'
                }, {
                    x : Date.UTC(2013, 5, 1),
                    title : '$',
                    text : '我要努力賺錢'
                }],
                onSeries: 'twii',
                shape: 'circlepin',
                width: 16
            }]
		});
	});
});

		</script>
</head>
<body>

<div id="info"></div>
<div id="container" style="height: 800px; min-width: 250px"></div>
    
<script src="/webroot/js/highstock/highstock.src.js"></script>
<script src="/webroot/js/highstock/modules/exporting.js"></script>
<script src="/webroot/js/highstock/themes/grid.js"></script>
<script src="/webroot/js/xdate.js"></script>
<script src="/webroot/js/underscore-min.js"></script>
</body>
</html>
