<!DOCTYPE html>
<meta charset="utf-8">
<style>/*{{{*/

    body {
        font: 10px sans-serif;
    }

    text {
        fill: #000;
    }

    path {
        fill: none;
        stroke-width: 1;
    }

    path.candle {
        stroke: #000000;
    }

    path.candle.body {
        stroke-width: 1;
    }

    path.candle.down {
        fill: #00AA00;
        stroke: #000000;
    }

    path.candle.up {
        fill: #FF0000;
        stroke: #000000;
    }

    .ma-0 path.line {
        stroke: #1f77b4;
    }

    .ma-1 path.line {
        stroke: #aec7e8;
    }

    path.volume {
        fill: #EEEEEE;
    }

    .crosshair {
        cursor: crosshair;
    }

    .crosshair path.wire {
        stroke: #DDDDDD;
        stroke-dasharray: 1, 1;
    }

    .crosshair .axisannotation path {
        fill: #DDDDDD;
    }

</style><!--/*}}}*/-->
<body>
<script src="http://d3js.org/d3.v4.min.js"></script>
<script src="http://techanjs.org/techan.min.js"></script>
<script>

    var margin = {top: 20, right: 20, bottom: 30, left: 50},
            width = 960 - margin.left - margin.right,
            height = 500 - margin.top - margin.bottom;

    var parseTick = d3.timeParse("%Y/%m/%d %H:%M:%S");
    var parseDate = d3.timeParse("%Y/%m/%d");

    var x = techan.scale.financetime()
            .range([0, width]);

    var y = d3.scaleLinear()
            .range([height, 0]);

    var yVolume = d3.scaleLinear()
            .range([y(0), y(0.2)]);

    var candlestick = techan.plot.candlestick()
            .xScale(x)
            .yScale(y);

    var sma0 = techan.plot.sma()
            .xScale(x)
            .yScale(y);

    var sma0Calculator = techan.indicator.sma()
            .period(10);

    var sma1 = techan.plot.sma()
            .xScale(x)
            .yScale(y);

    var sma1Calculator = techan.indicator.sma()
            .period(20);

    var volume = techan.plot.volume()
            .accessor(candlestick.accessor())   // Set the accessor to a candlestick accessor so we get highlighted bars
            .xScale(x)
            .yScale(yVolume);

    var xAxis = d3.axisBottom(x);

    var yAxis = d3.axisLeft(y);

    var volumeAxis = d3.axisRight(yVolume)
            .ticks(3)
            .tickFormat(d3.format(",.3s"));

    var timeAnnotation = techan.plot.axisannotation()
            .axis(xAxis)
            .orient('bottom')
            .format(d3.timeFormat('%Y-%m-%d %H:%M'))
            .width(65)
            .translate([0, height]);

    var candlestickAnnotation = techan.plot.axisannotation()
            .axis(yAxis)
            .orient('left')
            .format(d3.format(',.2f'));

    var volumeAnnotation = techan.plot.axisannotation()
            .axis(volumeAxis)
            .orient('right')
            .width(35);

    var crosshair = techan.plot.crosshair()
            .xScale(x)
            .yScale(y)
            .xAnnotation(timeAnnotation)
            .yAnnotation([candlestickAnnotation, volumeAnnotation])
            .on("move", move);

    var svg = d3.select("body").append("svg")
            .attr("width", width + margin.left + margin.right)
            .attr("height", height + margin.top + margin.bottom);

    var defs = svg.append("defs");

    defs.append("clipPath")
            .attr("id", "candlestickClip")
        .append("rect")
            .attr("x", 0)
            .attr("y", 0)
            .attr("width", width)
            .attr("height", height);

    svg = svg.append("g")
            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    var candlestickSelection = svg.append("g")
            .attr("class", "candlestick")
            .attr("transform", "translate(0,0)");

    candlestickSelection.append("g")
            .attr("class", "volume")
            .attr("clip-path", "url(#candlestickClip)");

    candlestickSelection.append("g")
            .attr("class", "candlestick")
            .attr("clip-path", "url(#candlestickClip)");

    candlestickSelection.append("g")
            .attr("class", "indicator sma ma-0")
            .attr("clip-path", "url(#candlestickClip)");

    candlestickSelection.append("g")
            .attr("class", "indicator sma ma-1")
            .attr("clip-path", "url(#candlestickClip)");

    svg.append("g")
            .attr("class", "x axis")
            .attr("transform", "translate(0," + height + ")");

    svg.append("g")
            .attr("class", "y axis")
            .append("text")
            .attr("transform", "rotate(-90)")
            .attr("y", 6)
            .attr("dy", ".71em")
            .style("text-anchor", "end")
            .text("Price ($)");

    svg.append("g")
            .attr("class", "volume axis");

    svg.append('g')
            .attr("class", "crosshair candlestick");

    var coordsText = svg.append('text')
            .style("text-anchor", "end")
            .attr("class", "coords")
            .attr("x", width - 5)
            .attr("y", 15);

    var feed;

    //d3.csv("/webroot/data.csv", function(error, csv) {
    d3.json("/ajax/realtime", function(error, data) {
        var accessor = candlestick.accessor();

        feed = data.map(function(d) {
            return {
                date: parseDate(d[0]),
                open: +d[1],
                high: +d[2],
                low: +d[3],
                close: +d[4],
                volume: +d[5]
            };
        }).sort(function(a, b) { return d3.ascending(accessor.d(a), accessor.d(b)); });

        d3.json("/ajax/tick", function(error, tick) {
            console.log(tick);
            var last = {
                date: parseTick(tick.time),
                open: tick.open,
                high: tick.top,
                low: tick.low,
                close: tick.close,
                volume: tick.volume
            };
            feed.push(last);

            // Start off an initial set of data
            redraw(feed);
        });

    });

    function redraw(data) {
        var accessor = candlestick.accessor();

        x.domain(data.map(accessor.d));
        // Show only 150 points on the plot
        x.zoomable().domain([data.length-130, data.length]);

        // Update y scale min max, only on viewable zoomable.domain()
        y.domain(techan.scale.plot.ohlc(data.slice(data.length-130, data.length)).domain());
        yVolume.domain(techan.scale.plot.volume(data.slice(data.length-130, data.length)).domain());

        // Setup a transition for all that support
        svg
//          .transition() // Disable transition for now, each is only for transitions
            .each(function() {
                var selection = d3.select(this);
                selection.select('g.x.axis').call(xAxis);
                selection.select('g.y.axis').call(yAxis);
                selection.select("g.volume.axis").call(volumeAxis);

                selection.select("g.candlestick").datum(data).call(candlestick);
                selection.select("g.sma.ma-0").datum(sma0Calculator(data)).call(sma0);
                selection.select("g.sma.ma-1").datum(sma1Calculator(data)).call(sma1);
                selection.select("g.volume").datum(data).call(volume);

                svg.select("g.crosshair.candlestick").call(crosshair);
            });

        // Set next timer expiry
        setTimeout(function() {
            var newData;

            if(data.length < feed.length) {
                // Simulate a daily feed
                newData = feed.slice(0, data.length+1);
                redraw(newData);
            }
            else {
                // Simulate intra day updates when no feed is left
                var last = data[data.length-1];

                d3.json("/ajax/tick", function(error, tick) {
                    console.log(tick);
                    last.open = tick.open;
                    last.high = tick.top;
                    last.low = tick.low;
                    last.close = tick.close;
                    last.volume = tick.volume;

                    newData = data;
                    redraw(newData);
                });
            }

        }, 5000); 
    }

    function move(coords) {
        coordsText.text(
                timeAnnotation.format()(coords.x) + ", " + candlestickAnnotation.format()(coords.y)
        );
    }

</script>
