<style type="text/css">
table#dayinfo {
    font-family: verdana,arial,sans-serif;
    font-size:11px;
    color:#333333;
    border-width: 1px;
    border-color: #666666;
    border-collapse: collapse;
}
table#dayinfo th {
    width: 60px;
    border-width: 1px;
    padding: 8px;
    border-style: solid;
    border-color: #666666;
    background-color: #dedede;
}
table#dayinfo td {
    border-width: 1px;
    padding: 8px;
    border-style: solid;
    border-color: #666666;
    background-color: #ffffff;
}
</style>
<?php
$day = $yestoday = $this->day;
while ($yestoday = $yestoday - 86400) {
    $row = FutureContract::search(array('date' => $yestoday));
    if (sizeof($row)) {
        break;
    }
}
?>
<table id="dayinfo">
    <tr>
        <th colspan="2"><?= date('Y/m/d', $day); ?></th>
        <th colspan="6">自營</th>
        <th colspan="6">外資</th>
    </tr>
    <tr>
        <th colspan="2"></th>
        <th colspan="2">庫存</th>
        <th colspan="2">與前日比較</th>
        <th colspan="2"></th>
        <th colspan="2">庫存</th>
        <th colspan="2">與前日比較</th>
        <th colspan="2"></th>
    </tr>
    <tr>
        <th>日期</th>
        <th>商品</th>
        <th>買方</th>
        <th>賣方</th>
        <th>買方</th>
        <th>賣方</th>
        <th>淨部位</th>
        <th>淨部位變化</th>
        <th>買方</th>
        <th>賣方</th>
        <th>買方</th>
        <th>賣方</th>
        <th>淨部位</th>
        <th>淨部位變化</th>
    </tr>
    <?= $this->partial('/ajax/dayinfo_row.phtml', array('today' => $yestoday)); ?>
    <?= $this->partial('/ajax/dayinfo_row.phtml', array('today' => $day)); ?>
</table>
