<?php
$today = $this->today;
$future_1 = FutureContract::search(array('date' => $today, 'user_id' => 1))->first();
if (sizeof($future_1)) {
    $future_1_yestoday = $future_1->previous();
    $option_1 = OptionContract::search(array('date' => $today, 'user_id' => 1))->first();
    $option_1_yestoday = $option_1->previous();

    $future_3 = FutureContract::search(array('date' => $today, 'user_id' => 3))->first();
    $future_3_yestoday = $future_3->previous();
    $option_3 = OptionContract::search(array('date' => $today, 'user_id' => 3))->first();
    $option_3_yestoday = $option_3->previous();
?>
<tr <?= ($this->bgColor) ? 'class="day_background"' : ''?>>
    <td><?= date('Y/m/d', $today); ?></td>
    <td style="color:#0000FF">台指期貨</td>
    <td title="<?=$future_3->detail('buy'); ?>"><?= $future_3->buy; ?></td>
    <td title="<?=$future_3->detail('sell'); ?>"><?= $future_3->sell; ?></td>
    <td><?= $future_3->buy - $future_3_yestoday->buy; ?></td>
    <td><?= $future_3->sell - $future_3_yestoday->sell; ?></td>
    <td><?= $future_3->buy - $future_3->sell; ?></td>
    <?php $outside_futures = ($future_3->buy - $future_3->sell) - ($future_3_yestoday->buy - $future_3_yestoday->sell);?>
    <td style="color:#<?= ($outside_futures > 0) ? 'FF0000' : '00FF00'?>"><?= $outside_futures ?></td>
    <td title="<?=$future_1->detail('buy'); ?>"><?= $future_1->buy; ?></td>
    <td title="<?=$future_1->detail('sell'); ?>"><?= $future_1->sell; ?></td>
    <td><?= $future_1->buy - $future_1_yestoday->buy; ?></td>
    <td><?= $future_1->sell - $future_1_yestoday->sell; ?></td>
    <td><?= $future_1->buy - $future_1->sell; ?></td>
    <?php $inside_futures = ($future_1->buy - $future_1->sell) - ($future_1_yestoday->buy - $future_1_yestoday->sell); ?>
    <td style="color:#<?= ($inside_futures > 0) ? 'FF0000' : '00FF00'?>"><?= $inside_futures ?></td>
</tr>
<tr <?= ($this->bgColor) ? 'class="day_background"' : ''?>>
    <td></td>
    <td style="color:#FF0000">台指買權</td>
    <td title="<?=$option_3->detail('buycall'); ?>"><?= $option_3->buycall; ?></td>
    <td title="<?=$option_3->detail('sellcall'); ?>"><?= $option_3->sellcall; ?></td>
    <td><?= $option_3->buycall - $option_3_yestoday->buycall; ?></td>
    <td><?= $option_3->sellcall - $option_3_yestoday->sellcall; ?></td>
    <td><?= $option_3->buycall - $option_3->sellcall ?></td>
    <?php $outside_otp_buy = ($option_3->buycall - $option_3->sellcall) - ($option_3_yestoday->buycall - $option_3_yestoday->sellcall);?>
    <td style="color:#<?= ($outside_otp_buy > 0) ? 'FF0000' : '00FF00'?>"><?= $outside_otp_buy ?></td>
    <td title="<?=$option_1->detail('buycall'); ?>"><?= $option_1->buycall; ?></td>
    <td title="<?=$option_1->detail('sellcall'); ?>"><?= $option_1->sellcall; ?></td>
    <td><?= $option_1->buycall - $option_1_yestoday->buycall; ?></td>
    <td><?= $option_1->sellcall - $option_1_yestoday->sellcall; ?></td>
    <td><?= $option_1->buycall - $option_1->sellcall ?></td>
    <?php  $inside_otp_buy = ($option_1->buycall - $option_1->sellcall) - ($option_1_yestoday->buycall - $option_1_yestoday->sellcall);?>
    <td style="color:#<?= ($inside_otp_buy > 0) ? 'FF0000' : '00FF00'?>"><?= $inside_otp_buy ?></td>
</tr>
<tr <?= ($this->bgColor) ? 'class="day_background"' : ''?>>
    <td></td>
    <td style="color:#00FF00">台指賣權</td>
    <td title="<?=$option_3->detail('buyput'); ?>"><?= $option_3->buyput; ?></td>
    <td title="<?=$option_3->detail('sellput'); ?>"><?= $option_3->sellput; ?></td>
    <td><?= $option_3->buyput - $option_3_yestoday->buyput; ?></td>
    <td><?= $option_3->sellput - $option_3_yestoday->sellput; ?></td>
    <td><?= $option_3->buyput - $option_3->sellput ?></td>
    <?php $outside_otp_sell = ($option_3->buyput - $option_3->sellput) - ($option_3_yestoday->buyput - $option_3_yestoday->sellput);?>
    <td style="color:#<?= ($outside_otp_sell < 0) ? 'FF0000' : '00FF00'?>"><?= $outside_otp_sell ?></td>
    <td title="<?=$option_1->detail('buyput'); ?>"><?= $option_1->buyput; ?></td>
    <td title="<?=$option_1->detail('sellput'); ?>"><?= $option_1->sellput; ?></td>
    <td><?= $option_1->buyput - $option_1_yestoday->buyput; ?></td>
    <td><?= $option_1->sellput - $option_1_yestoday->sellput; ?></td>
    <td><?= $option_1->buyput - $option_1->sellput ?></td>
    <?php $inside_otp_sell = ($option_1->buyput - $option_1->sellput) - ($option_1_yestoday->buyput - $option_1_yestoday->sellput);?>
    <td style="color:#<?= ($inside_otp_sell < 0) ? 'FF0000' : '00FF00'?>"><?= $inside_otp_sell ?></td>
</tr>
<?php
}
?>
